# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  release-windows-amd64:
    name: release windows/amd64 go binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        project_path: "./"
        binary_name: "gosharex"
        ldflags: "-s -w"
